export interface Career {
  id: string;
  title: string;
  tagline: string;
  salaryRange: { min: number; max: number; entry: number };
  educationPath: string;
  educationCost: string;
  timeToEntry: string;
  values: string[];
  accessibilityScore: number;
  dayInTheLife: string;
  realPersonStory: {
    quote: string;
    name: string;
    age: number;
    background: string;
  };
  growthOutlook: "Growing fast" | "Stable" | "Competitive";
  localOpportunities: string;
  financialAidNote: string;
  onetUrl?: string;
  relatedCareerIds?: string[];
  pathSteps?: {
    grade11: string[];
    grade12: string[];
    graduated: string[];
  };
  startToday?: string[];
}

export const CAREERS: Career[] = [
  { id: "registered-nurse", title: "Registered Nurse (RN)", tagline: "Care for patients and keep families informed during hard moments.", salaryRange: { min: 62000, max: 115000, entry: 68000 }, educationPath: "Earn an ADN at community college or BSN, then pass the NCLEX-RN exam.", educationCost: "$8,000-$45,000 total, depending on community college vs university route and grants.", timeToEntry: "2-4 years", values: ["health", "helping", "stability", "money"], accessibilityScore: 7, dayInTheLife: "You start by checking each patient's chart and asking how they feel today. You give meds, explain next steps, and update doctors about changes. Some moments are intense, but your calm voice helps people breathe easier. At the end of your shift, you know your work mattered to real families.", realPersonStory: { quote: "I started at a community college in Houston while working weekends. Now I am an RN and helped my mom finally move into a safer apartment.", name: "Maria", age: 28, background: "First-gen daughter of a hotel housekeeper in Houston, TX" }, growthOutlook: "Growing fast", localOpportunities: "Hospitals, school clinics, urgent care centers, and community health systems in almost every city.", financialAidNote: "Pell Grants can cover much of ADN tuition, and many hospitals offer tuition reimbursement once you are hired." },
  { id: "electrician", title: "Electrician", tagline: "Install and repair power systems in homes, schools, and businesses.", salaryRange: { min: 45000, max: 98000, entry: 48000 }, educationPath: "Join a paid apprenticeship through a union, trade school, or workforce program.", educationCost: "$1,000-$12,000 for pre-apprenticeship classes, with paid on-the-job training afterward.", timeToEntry: "6 months to start, 4 years to journeyman", values: ["technology", "independence", "stability", "money"], accessibilityScore: 9, dayInTheLife: "Your morning starts with a job site plan and safety check. You run wiring, install breakers, and test outlets so families and businesses have safe power. You move around a lot, solve practical problems, and work with your hands all day. No two projects feel exactly the same.", realPersonStory: { quote: "I thought college was the only way to make real money. My apprenticeship in Detroit paid me while I learned, and now I cover rent and help with my brother's books.", name: "Darnell", age: 26, background: "Grew up in Detroit, MI in a single-parent household" }, growthOutlook: "Growing fast", localOpportunities: "Residential contractors, city maintenance departments, school districts, and renewable energy installers.", financialAidNote: "Workforce Innovation grants and trade scholarships can pay for pre-apprenticeship fees, tools, and exam costs." },
  { id: "social-worker", title: "Social Worker", tagline: "Help people navigate housing, school, health, and crisis support systems.", salaryRange: { min: 43000, max: 78000, entry: 47000 }, educationPath: "Complete a BSW, then add state licensure; some roles allow entry sooner as a case aide.", educationCost: "$12,000-$50,000 depending on in-state public school and aid package.", timeToEntry: "4 years", values: ["justice", "helping", "community", "family"], accessibilityScore: 6, dayInTheLife: "You meet students, parents, or elders and listen to what is really going on. Then you connect them to housing help, food support, counseling, or legal resources. Paperwork is part of it, but your main job is helping people feel less alone. You become the person who knows how to get things done.", realPersonStory: { quote: "My counselor changed my life in high school, so I became that person for other kids in Phoenix. It is hard work, but every graduation feels personal.", name: "Elena", age: 31, background: "First-gen college grad from a public housing neighborhood in Phoenix, AZ" }, growthOutlook: "Growing fast", localOpportunities: "Public schools, nonprofit agencies, county family services, and hospital social work teams.", financialAidNote: "Pell Grants and state tuition programs can lower BSW costs, and some agencies repay loans after licensure." },
  { id: "ux-designer", title: "UX Designer", tagline: "Design apps and websites that are easy for real people to use.", salaryRange: { min: 58000, max: 130000, entry: 62000 }, educationPath: "Build a portfolio through community college, bootcamp, or self-paced projects plus internships.", educationCost: "$3,000-$25,000 depending on certificate or degree route.", timeToEntry: "1-4 years", values: ["creativity", "technology", "learning", "expression"], accessibilityScore: 6, dayInTheLife: "You interview users, sketch screens, and test what confuses people. Then you redesign buttons, flows, and wording so tasks feel simple. You work with developers and product teams to ship updates. It is creative and problem-solving at the same time.", realPersonStory: { quote: "I learned design at a community college in San Antonio and built my portfolio on free tools at the library. Now I design health apps my own family can actually understand.", name: "Jasmine", age: 25, background: "First-gen Latina from San Antonio, TX" }, growthOutlook: "Competitive", localOpportunities: "Hospitals, city services, startups, banks, and school tech vendors all need better digital experiences.", financialAidNote: "Pell Grants can fund community college design courses, and workforce scholarships often cover UX certificates." },
  { id: "medical-assistant", title: "Medical Assistant", tagline: "Support clinics by taking vitals, scheduling visits, and helping patients feel ready.", salaryRange: { min: 34000, max: 56000, entry: 38000 }, educationPath: "Complete a 9-18 month certificate at a community college or accredited training center.", educationCost: "$2,500-$12,000 with grant options at public colleges.", timeToEntry: "9-18 months", values: ["health", "helping", "stability", "family"], accessibilityScore: 9, dayInTheLife: "You greet patients, take blood pressure, and prep exam rooms before the provider walks in. You explain simple instructions, update records, and make sure people know their next appointment. It is fast-paced but very human. You become a familiar, trusted face in your community clinic.", realPersonStory: { quote: "I finished my certificate in one year in Fresno and started earning right away. That paycheck helped us stop bouncing between apartments.", name: "Rosa", age: 24, background: "Raised by grandparents in Fresno, CA" }, growthOutlook: "Growing fast", localOpportunities: "Community clinics, urgent cares, pediatric offices, and specialty practices in most neighborhoods.", financialAidNote: "Pell Grants and local workforce grants often cover short-term medical assistant certificates fully." },
  { id: "paralegal", title: "Paralegal", tagline: "Support attorneys by organizing cases, documents, and client timelines.", salaryRange: { min: 42000, max: 82000, entry: 46000 }, educationPath: "Earn an associate degree or certificate in paralegal studies, then build experience in a legal office.", educationCost: "$4,000-$20,000 at community colleges and public institutions.", timeToEntry: "1-2 years", values: ["justice", "learning", "stability", "recognition"], accessibilityScore: 8, dayInTheLife: "You review case files, prepare court forms, and track deadlines that cannot be missed. You call clients, gather facts, and help lawyers stay organized for hearings. The work is detail-heavy, but you learn how the legal system really works. Every case teaches you something new.", realPersonStory: { quote: "I was the first in my family to work in a law office. Starting as a paralegal in Newark gave me stable pay and a path to keep growing.", name: "Imani", age: 27, background: "First-gen college student from Newark, NJ" }, growthOutlook: "Stable", localOpportunities: "Legal aid clinics, immigration nonprofits, district attorney offices, and private law firms.", financialAidNote: "Pell Grants can cover community college legal studies programs, and some legal aid orgs offer paid training roles." },
  { id: "hvac-technician", title: "HVAC Technician", tagline: "Keep heating and cooling systems running in homes and businesses.", salaryRange: { min: 42000, max: 85000, entry: 45000 }, educationPath: "Train through a 6-12 month trade program, then apprentice and earn certifications.", educationCost: "$3,000-$15,000 for training, often reduced by grants.", timeToEntry: "6-12 months", values: ["independence", "stability", "technology", "money"], accessibilityScore: 9, dayInTheLife: "You troubleshoot why an AC stopped working or why a heater is blowing cold air. You inspect systems, replace parts, and explain fixes to customers in plain words. The work is active and practical, and you can see your impact right away. People are genuinely relieved when you show up.", realPersonStory: { quote: "I started HVAC classes at night in Tampa while stocking shelves during the day. Two years later I bought my first used truck with cash.", name: "Noah", age: 29, background: "First-gen worker from Tampa, FL" }, growthOutlook: "Growing fast", localOpportunities: "Local contractors, apartment maintenance teams, hospitals, schools, and city buildings.", financialAidNote: "State workforce grants and trade school scholarships can cover tuition, tools, and EPA exam fees." },
  { id: "elementary-teacher", title: "Elementary School Teacher", tagline: "Teach core skills and help kids believe in themselves early.", salaryRange: { min: 42000, max: 78000, entry: 46000 }, educationPath: "Complete a bachelor's plus teacher prep program and state licensure exams.", educationCost: "$15,000-$55,000 with in-state options and grants.", timeToEntry: "4 years", values: ["helping", "community", "family", "learning"], accessibilityScore: 6, dayInTheLife: "You teach reading, math, and routines that help kids feel safe and ready to learn. Some days are loud and messy, but small wins happen constantly. You meet families, plan lessons, and adjust for different learning needs. You are building confidence, not just test scores.", realPersonStory: { quote: "I grew up in Albuquerque public schools and came back to teach third grade here. Seeing my students light up when reading clicks is everything.", name: "Kayla", age: 30, background: "First-gen college graduate from Albuquerque, NM" }, growthOutlook: "Stable", localOpportunities: "Public schools, charter schools, after-school programs, and district education offices.", financialAidNote: "Pell Grants and TEACH Grants can reduce school costs, and some districts offer loan support for high-need schools." },
  { id: "cybersecurity-analyst", title: "Cybersecurity Analyst", tagline: "Protect companies and communities from online attacks and scams.", salaryRange: { min: 70000, max: 145000, entry: 76000 }, educationPath: "Start with community college IT courses, then earn CompTIA Security+ and build hands-on labs.", educationCost: "$4,000-$22,000 plus certification exam fees.", timeToEntry: "1-4 years", values: ["technology", "learning", "stability", "money"], accessibilityScore: 7, dayInTheLife: "You watch alerts, investigate suspicious logins, and block threats before damage spreads. You document incidents and help teams strengthen passwords and systems. It can feel like solving a mystery every day. Your work protects real people from losing money and data.", realPersonStory: { quote: "I learned IT at a community college in Baltimore and studied for Security+ with free YouTube labs. My first analyst job changed my whole family's money situation.", name: "Malik", age: 27, background: "First-gen son of immigrants in Baltimore, MD" }, growthOutlook: "Growing fast", localOpportunities: "Hospitals, banks, schools, city agencies, and managed security firms hire entry analysts.", financialAidNote: "Workforce grants often pay for cybersecurity certificates and exams like Security+ and Network+." },
  { id: "dental-hygienist", title: "Dental Hygienist", tagline: "Clean teeth, teach oral health, and catch problems early.", salaryRange: { min: 62000, max: 108000, entry: 70000 }, educationPath: "Complete an accredited associate degree in dental hygiene and pass licensure exams.", educationCost: "$8,000-$35,000 depending on public vs private program.", timeToEntry: "2-3 years", values: ["health", "helping", "stability", "money"], accessibilityScore: 7, dayInTheLife: "You clean teeth, take x-rays, and show patients how to prevent painful issues. You work closely with dentists but spend lots of one-on-one time with people. Many patients are nervous, and your calm energy matters. It is steady healthcare work with strong pay.", realPersonStory: { quote: "I chose community college in Charlotte because it was affordable and close to my family. Dental hygiene gave me stable hours and enough income to save.", name: "Tiana", age: 29, background: "First-gen Black woman from Charlotte, NC" }, growthOutlook: "Stable", localOpportunities: "Neighborhood dental offices, school dental programs, community clinics, and mobile dental units.", financialAidNote: "Pell Grants and state need-based aid can significantly reduce associate program tuition at public colleges." },
  { id: "graphic-designer", title: "Graphic Designer", tagline: "Create visuals for brands, social posts, products, and campaigns.", salaryRange: { min: 38000, max: 86000, entry: 42000 }, educationPath: "Build a portfolio through community college design classes, certifications, freelancing, and internships.", educationCost: "$2,000-$20,000 depending on route and software access.", timeToEntry: "1-4 years", values: ["creativity", "expression", "independence", "technology"], accessibilityScore: 6, dayInTheLife: "You design logos, flyers, social graphics, and layouts that grab attention fast. You meet with clients or teammates, revise drafts, and keep projects on deadline. Some days are all creative flow, other days are feedback and edits. You get to turn ideas into visuals people remember.", realPersonStory: { quote: "I learned design at my local library computer lab in Cleveland and built a freelance client list before graduating. That portfolio got me hired full-time.", name: "Andre", age: 24, background: "First-gen college student from Cleveland, OH" }, growthOutlook: "Competitive", localOpportunities: "Small businesses, nonprofits, schools, city communication teams, and marketing agencies.", financialAidNote: "Pell Grants can fund community college classes, and many cities offer microgrants for creative workforce training." },
  { id: "construction-manager", title: "Construction Manager", tagline: "Lead building projects, crews, schedules, and budgets from start to finish.", salaryRange: { min: 65000, max: 125000, entry: 70000 }, educationPath: "Begin in skilled trades or construction tech programs, then move into supervisor and manager roles.", educationCost: "$2,000-$30,000 depending on certificate, associate, or bachelor's path.", timeToEntry: "2-6 years", values: ["leadership", "money", "independence", "stability"], accessibilityScore: 7, dayInTheLife: "You run morning site meetings, set priorities, and keep crews on schedule safely. You coordinate materials, inspect progress, and solve surprises quickly. You talk with electricians, plumbers, owners, and city inspectors in the same day. It is leadership in motion.", realPersonStory: { quote: "I started as a laborer in Atlanta and took night classes in construction management. Now I run projects and mentor younger workers from my neighborhood.", name: "DeShawn", age: 33, background: "Grew up low-income in Atlanta, GA" }, growthOutlook: "Stable", localOpportunities: "General contractors, city infrastructure projects, school renovations, and affordable housing builds.", financialAidNote: "Apprenticeships pay while you learn, and workforce grants can cover supervisor certifications and construction coursework." },
  { id: "community-health-worker", title: "Community Health Worker", tagline: "Help neighbors connect to healthcare, food, housing, and support services.", salaryRange: { min: 35000, max: 62000, entry: 39000 }, educationPath: "Complete a short certification and train on the job through clinics or nonprofits.", educationCost: "$500-$6,000 for certificate programs, often grant-funded.", timeToEntry: "3-12 months", values: ["justice", "health", "community", "helping"], accessibilityScore: 10, dayInTheLife: "You check in with families, explain clinic services, and help them fill out forms they might not trust alone. You connect people to food programs, mental health support, and transportation. A lot of your work is listening and translating systems into real-life steps. You become a bridge people count on.", realPersonStory: { quote: "I grew up in the same Bronx neighborhood I serve now. Helping neighbors navigate healthcare feels personal because my family needed that help too.", name: "Luz", age: 26, background: "First-gen Puerto Rican from the Bronx, NY" }, growthOutlook: "Growing fast", localOpportunities: "Federally qualified health centers, nonprofits, hospitals, and public health departments.", financialAidNote: "Many CHW programs are fully funded through workforce grants, and Pell Grants can support longer public health certificates." },
  { id: "software-developer", title: "Software Developer", tagline: "Build apps and tools people use every day.", salaryRange: { min: 70000, max: 160000, entry: 78000 }, educationPath: "Learn through community college, coding bootcamps, apprenticeships, or a CS degree plus projects.", educationCost: "$0-$40,000 depending on self-taught, community college, bootcamp, or degree path.", timeToEntry: "1-4 years", values: ["technology", "learning", "money", "creativity"], accessibilityScore: 7, dayInTheLife: "You write code, test features, and fix bugs users report. Team meetings help you plan what to build next and unblock problems. Some hours are deep focus, others are quick collaboration. You make products that can reach thousands of people.", realPersonStory: { quote: "I learned JavaScript from free online courses in Memphis and got my first internship through a nonprofit tech program. Now I work remote and help my family with bills every month.", name: "Nia", age: 25, background: "First-gen Black woman from Memphis, TN" }, growthOutlook: "Growing fast", localOpportunities: "Healthcare systems, banks, logistics companies, startups, and city tech teams.", financialAidNote: "Pell Grants can support community college CS credits, and workforce tech grants often cover bootcamp tuition for low-income learners." },
  { id: "plumber", title: "Plumber", tagline: "Install and repair water systems that homes and buildings rely on.", salaryRange: { min: 46000, max: 99000, entry: 50000 }, educationPath: "Start with trade training or direct apprenticeship and work toward journeyman licensing.", educationCost: "$1,000-$10,000 before paid apprenticeship income.", timeToEntry: "6 months to start, 4-5 years to license", values: ["independence", "stability", "money", "technology"], accessibilityScore: 9, dayInTheLife: "You diagnose leaks, replace fixtures, and install piping in homes or job sites. You work with tools, read building plans, and solve problems quickly. Customers call when things are urgent, so your skills are always needed. Many plumbers later open their own businesses.", realPersonStory: { quote: "My uncle showed me basic plumbing in El Paso, then I joined an apprenticeship. I now earn enough to support my daughter and save each month.", name: "Luis", age: 30, background: "First-gen dad from El Paso, TX" }, growthOutlook: "Stable", localOpportunities: "Local service companies, school facilities, hospitals, apartment complexes, and city infrastructure teams.", financialAidNote: "Trade scholarships and workforce grants often pay for classroom hours, tools, and licensing exam fees." },
  { id: "youth-counselor", title: "Youth Counselor", tagline: "Support teens through school stress, family changes, and life decisions.", salaryRange: { min: 38000, max: 68000, entry: 42000 }, educationPath: "Begin with an associate or bachelor's in human services, then pursue counseling credentials.", educationCost: "$8,000-$45,000 based on school choice and aid.", timeToEntry: "2-4 years", values: ["helping", "justice", "community", "family"], accessibilityScore: 7, dayInTheLife: "You run one-on-one check-ins and small group sessions with teens. You help students set goals, manage stress, and build plans after setbacks. Some days are emotional, but your support can change someone's direction. You are often the adult who listens without judgment.", realPersonStory: { quote: "I almost dropped out in high school, so I came back to serve students in Oakland who feel unseen. This work reminds me healing is possible.", name: "Aaliyah", age: 28, background: "First-gen graduate from Oakland, CA" }, growthOutlook: "Growing fast", localOpportunities: "Schools, community centers, juvenile programs, and youth-serving nonprofits.", financialAidNote: "Pell Grants help with public college human services programs, and many nonprofits offer paid trainee counselor roles." },
  { id: "firefighter", title: "Firefighter", tagline: "Respond to emergencies and protect people during dangerous situations.", salaryRange: { min: 44000, max: 90000, entry: 50000 }, educationPath: "Complete EMT training, pass physical and written exams, then fire academy.", educationCost: "$2,000-$15,000 depending on EMT and academy fees.", timeToEntry: "1-2 years", values: ["helping", "adventure", "community", "justice"], accessibilityScore: 8, dayInTheLife: "You check equipment, train with your crew, and stay ready for emergency calls. Calls can include fires, crashes, medical incidents, or public safety support. Teamwork is everything, and your shift can go from quiet to intense in seconds. You leave knowing you protected your city.", realPersonStory: { quote: "I trained as an EMT in Kansas City while working nights. Becoming a firefighter gave me a mission and a stable future.", name: "Terrence", age: 32, background: "First-gen public servant from Kansas City, MO" }, growthOutlook: "Stable", localOpportunities: "City fire departments, airport fire units, industrial safety teams, and wildland response crews.", financialAidNote: "Workforce grants often pay for EMT certification, and some departments reimburse academy costs after hiring." },
  { id: "podcast-content-creator", title: "Podcast / Content Creator", tagline: "Create stories, videos, and podcasts that build an audience and income.", salaryRange: { min: 28000, max: 120000, entry: 32000 }, educationPath: "Learn by producing content consistently, using low-cost gear, and adding media certificates.", educationCost: "$0-$8,000 depending on equipment and optional classes.", timeToEntry: "3 months to start, 2-5 years to scale", values: ["expression", "creativity", "independence", "adventure"], accessibilityScore: 7, dayInTheLife: "You plan episodes or posts, record content, edit clips, and publish on a schedule. You study what your audience likes and improve each week. Income can come from freelance work, sponsorships, and brand projects over time. It takes discipline, but your voice can reach people globally.", realPersonStory: { quote: "I started recording on my phone in New Orleans because I had no studio money. Three years later my podcast pays rent and opened doors I never expected.", name: "Zuri", age: 24, background: "First-gen creator from New Orleans, LA" }, growthOutlook: "Competitive", localOpportunities: "Local businesses, nonprofits, schools, and startups need social media and podcast production support.", financialAidNote: "Community media grants and workforce creative scholarships can help pay for editing software and equipment." },
  { id: "pharmacy-technician", title: "Pharmacy Technician", tagline: "Prepare medications and support pharmacists serving patients daily.", salaryRange: { min: 36000, max: 58000, entry: 40000 }, educationPath: "Complete a short pharmacy tech program and pass national certification.", educationCost: "$1,000-$8,000 for training and exam prep.", timeToEntry: "6-12 months", values: ["health", "stability", "helping", "learning"], accessibilityScore: 9, dayInTheLife: "You fill prescriptions, manage inventory, and double-check labels with the pharmacist. You answer customer questions about pickups and insurance steps. Accuracy matters because small mistakes can hurt someone. It is a strong healthcare entry point with clear next steps.", realPersonStory: { quote: "I took a pharmacy tech class in Indianapolis while caring for my younger cousins. The schedule worked for my life, and I landed a job right after certification.", name: "Brianna", age: 23, background: "First-gen caregiver from Indianapolis, IN" }, growthOutlook: "Stable", localOpportunities: "Retail pharmacies, hospital pharmacies, mail-order medication centers, and clinic systems.", financialAidNote: "Pell Grants and workforce grants can cover short certificate tuition, books, and certification exam costs." },
  { id: "environmental-technician", title: "Environmental Technician", tagline: "Test water, soil, and air to keep communities and nature safer.", salaryRange: { min: 40000, max: 76000, entry: 44000 }, educationPath: "Earn an environmental science or technician certificate/associate and train in field sampling.", educationCost: "$3,000-$18,000 through public colleges and certificates.", timeToEntry: "1-2 years", values: ["nature", "learning", "justice", "stability"], accessibilityScore: 8, dayInTheLife: "You collect samples from rivers, soil sites, or industrial areas and run tests in a lab. You track pollution levels and help teams follow safety rules. Some days are outdoors, others are data and reports. Your work helps protect neighborhoods from hidden hazards.", realPersonStory: { quote: "Growing up near refineries in Baton Rouge made this work personal for me. I now test water quality and advocate for cleaner blocks like mine.", name: "Camille", age: 27, background: "First-gen scientist from Baton Rouge, LA" }, growthOutlook: "Growing fast", localOpportunities: "City water departments, environmental consulting firms, utilities, and public health labs.", financialAidNote: "Pell Grants can fund associate programs, and green-jobs workforce grants often support field certification costs." },
  { id: "cna", title: "Certified Nursing Assistant (CNA)", tagline: "You are the person patients see most, helping with comfort and daily care.", salaryRange: { min: 31000, max: 48000, entry: 34000 }, educationPath: "State-approved CNA certification program, usually 4-12 weeks. No degree required.", educationCost: "$500-$1,500. Many employers sponsor training fully.", timeToEntry: "4-12 weeks", values: ["health", "helping", "stability", "family"], accessibilityScore: 10, dayInTheLife: "You check assigned patients, take vitals, help with meals and mobility, and make sure people are safe and comfortable. It is physical and personal care work that makes a visible impact every shift.", realPersonStory: { quote: "I finished a free CNA program in six weeks and started earning right away. My employer now helps pay for nursing school.", name: "Destiny", age: 22, background: "Grew up in Detroit; first in family in healthcare" }, growthOutlook: "Stable", localOpportunities: "Nursing homes, hospitals, rehab centers, and home health agencies in every city.", financialAidNote: "WIOA grants and employer-sponsored training often cover the full CNA path.", onetUrl: "https://www.onetonline.org/link/summary/31-1131.00", pathSteps: { grade11: ["Find free or low-cost CNA programs near you and ask about summer cohorts.", "Complete certification during summer if possible.", "Apply for part-time CNA shifts during 12th grade.", "After graduation, move into full-time CNA work and ask about RN bridge support.", "Use employer tuition help to move toward LPN or RN."], grade12: ["Apply now to a CNA program with evening/weekend options.", "Finish certification before or right after graduation.", "Start work in a hospital or long-term care center.", "Ask your employer about tuition reimbursement plans.", "Advance into LPN/RN training within 2-3 years."], graduated: ["Enroll this month in a CNA cohort starting soon.", "Complete certification and state testing quickly.", "Begin your first CNA role and build experience.", "Use employer support for next credential.", "Move toward LPN or RN for higher pay."] }, startToday: ["Search '[your city] free CNA training' and list three programs.", "Check local hospital and nursing home sites for 'CNA trainee' listings.", "Watch a real CNA shift vlog to see if the pace fits you."] },
  { id: "truck-driver", title: "CDL Truck Driver", tagline: "You move goods that keep communities running, and many companies pay to train you.", salaryRange: { min: 45000, max: 85000, entry: 55000 }, educationPath: "CDL-A program, usually 3-8 weeks. Company-sponsored paths are common.", educationCost: "$3,000-$7,000 if self-funded; many carriers train at no upfront cost.", timeToEntry: "3-8 weeks", values: ["independence", "money", "stability", "adventure"], accessibilityScore: 9, dayInTheLife: "You pick up loads, plan routes, log drive hours, and deliver on schedule. Regional routes can keep you close to home, while long-haul means more road time.", realPersonStory: { quote: "I switched from warehouse work to a company-paid CDL program and doubled my income in months.", name: "Marcus", age: 23, background: "From Memphis; entered trucking at 20" }, growthOutlook: "Growing fast", localOpportunities: "Distribution hubs, grocery suppliers, construction logistics, and regional routes nationwide.", financialAidNote: "WIOA grants and company-paid CDL tracks can remove most training costs.", onetUrl: "https://www.onetonline.org/link/summary/53-3032.00", pathSteps: { grade11: ["Learn state age requirements and CDL timeline.", "Study the CDL manual and prepare for permit.", "Take permit steps during 12th grade when eligible.", "Enroll after graduation in sponsored or grant-funded training.", "Build one clean driving year, then negotiate better routes/pay."], grade12: ["Start studying CDL materials now.", "Get learner permit when eligible.", "Join a paid/sponsored CDL program after graduation.", "Earn CDL-A and start regional or long-haul work.", "Use experience to move to higher-paying roles."], graduated: ["Apply this month to company-paid CDL programs.", "Complete training and licensing in 1-2 months.", "Start your first driving role quickly.", "Build your safety record and route flexibility.", "Move into higher-paying regional/specialized driving."] }, startToday: ["Download your state's free CDL handbook.", "Search 'company paid CDL training no experience'.", "Compare local vs regional route jobs to match your life."] },
  { id: "welder", title: "Welder", tagline: "You build and repair with metal, from structures to machines.", salaryRange: { min: 38000, max: 80000, entry: 42000 }, educationPath: "Trade certificate or apprenticeship, 6-18 months; certifications boost pay.", educationCost: "$5,000-$15,000 for school, often grant-funded; apprenticeships are paid.", timeToEntry: "6-18 months", values: ["technology", "independence", "stability", "money"], accessibilityScore: 8, dayInTheLife: "You read measurements and blueprints, prep materials, and weld safely with different techniques. Work can be in shops, outdoors, and on projects that demand precision.", realPersonStory: { quote: "After a 9-month community college program, I moved into a solid welding role and kept climbing with certifications.", name: "Jerome", age: 24, background: "From Gary, Indiana; family in manufacturing" }, growthOutlook: "Stable", localOpportunities: "Manufacturing plants, construction sites, fabrication shops, and infrastructure contractors.", financialAidNote: "Pell Grants and WIOA funding often cover welding certificates.", onetUrl: "https://www.onetonline.org/link/summary/51-4121.00", pathSteps: { grade11: ["Ask about school shop or welding exposure now.", "Visit a community college welding program this summer.", "Apply in 12th grade and complete FAFSA early.", "Earn first credential after graduation.", "Add certifications to increase pay quickly."], grade12: ["Apply to nearby welding programs now.", "Complete FAFSA and workforce grant paperwork.", "Start training after graduation.", "Earn certification and begin entry-level work.", "Stack specialty certs for higher wages."], graduated: ["Find the fastest-start welding certificate near you.", "Use grants to cover costs and complete training.", "Start welding work with first certification.", "Add second specialty certification.", "Move into higher-paying specialized welding."] }, startToday: ["Search local community college welding certificates.", "Visit aws.org for certification paths.", "Watch MIG vs TIG day-in-life videos and pick your lane."] },
  { id: "wind-turbine-tech", title: "Wind Turbine Technician", tagline: "You maintain turbines and keep renewable energy systems working.", salaryRange: { min: 46000, max: 95000, entry: 52000 }, educationPath: "Wind tech certificate or associate path, often 1-2 years.", educationCost: "$3,000-$12,000, usually reduced by Pell Grants.", timeToEntry: "1-2 years", values: ["technology", "nature", "adventure", "stability"], accessibilityScore: 7, dayInTheLife: "You inspect components, run diagnostics, replace parts, and work at height in changing weather. It is technical, physical, and team-based work.", realPersonStory: { quote: "I trained at community college and got hired before graduating into a role with strong pay growth.", name: "Andres", age: 23, background: "From Midland, Texas; first in family in energy" }, growthOutlook: "Growing fast", localOpportunities: "Wind farms in Texas, Midwest, Plains, and expanding coastal regions.", financialAidNote: "Pell Grants and school-industry partnerships often lower training costs and speed hiring.", onetUrl: "https://www.onetonline.org/link/summary/49-9081.00", pathSteps: { grade11: ["Research wind tech programs in your state.", "Review industry basics and job maps this summer.", "Apply during 12th grade and file FAFSA.", "Complete training after graduation.", "Add safety and electrical credentials for faster raises."], grade12: ["Find a wind technician program near you now.", "Apply and finish FAFSA before deadlines.", "Start training after graduation.", "Earn core certification during year 1.", "Move into higher-paying sites with experience."], graduated: ["Apply this month to nearest wind tech program.", "Complete program and safety certs.", "Join a wind company in field operations.", "Build diagnostics/electrical expertise.", "Advance to senior tech or supervisor track."] }, startToday: ["Search 'wind turbine technician program [state]'.", "Read DOE wind career guides.", "Watch real turbine maintenance videos to test fit."] },
  { id: "cosmetologist", title: "Cosmetologist / Barber", tagline: "You build a client base and turn creative skill into income.", salaryRange: { min: 28000, max: 75000, entry: 32000 }, educationPath: "State cosmetology or barber license, usually 9-18 months.", educationCost: "$5,000-$20,000, with Pell eligibility for accredited schools.", timeToEntry: "9-18 months", values: ["creativity", "independence", "expression", "community"], accessibilityScore: 8, dayInTheLife: "You work with clients on cuts, styles, color, and care while building trust and repeat business. Over time, many pros rent a chair or suite and control schedule and pricing.", realPersonStory: { quote: "I started doing friends' hair, got licensed, and now run my own suite with my own hours.", name: "Kiara", age: 26, background: "From Atlanta; built clientele from her neighborhood" }, growthOutlook: "Stable", localOpportunities: "Barbershops, salons, suites, and neighborhood beauty businesses in every city.", financialAidNote: "Pell Grants can cover accredited cosmetology programs; state workforce grants may also apply.", onetUrl: "https://www.onetonline.org/link/summary/39-5012.00", pathSteps: { grade11: ["Research accredited programs with strong board pass rates.", "Visit schools and ask about schedules and aid.", "Apply in 12th grade and complete FAFSA.", "Finish hours and pass state board after graduation.", "Grow client base and move toward booth rental."], grade12: ["Apply to accredited programs now.", "Confirm FAFSA/Pell eligibility before enrolling.", "Start training after graduation.", "Complete hours and licensing exam.", "Build returning clients and raise rates over time."], graduated: ["Find accredited school start dates this month.", "Complete training and exam prep.", "Get licensed and start in a shop quickly.", "Build repeat clients and referrals.", "Transition to independent suite/chair model."] }, startToday: ["Check your state licensing board requirements.", "Follow top stylists in your city to study how they market.", "Practice on willing friends/family and document your work."] },
  { id: "military", title: "Military Enlistment", tagline: "Structured service with paycheck, housing, healthcare, and training.", salaryRange: { min: 25000, max: 70000, entry: 30000 }, educationPath: "HS diploma/GED plus ASVAB, then basic training and specialty training.", educationCost: "No tuition cost; service members are paid and receive housing and healthcare.", timeToEntry: "3-6 months", values: ["stability", "leadership", "community", "adventure"], accessibilityScore: 10, dayInTheLife: "Daily life varies by role: IT, healthcare, logistics, engineering, and more. Training is structured and team-focused, with benefits that support long-term goals.", realPersonStory: { quote: "Service gave me training, steady pay, and GI Bill support that set up my next chapter without debt.", name: "DeShawn", age: 26, background: "From Baltimore; enlisted after high school" }, growthOutlook: "Stable", localOpportunities: "Recruitment and National Guard opportunities in all states.", financialAidNote: "GI Bill and Tuition Assistance can fund college/training during and after service.", onetUrl: "https://www.onetonline.org/link/summary/55-1019.00", pathSteps: { grade11: ["Take a free ASVAB practice test and review job options.", "Talk with recruiters from multiple branches to compare.", "Use 12th grade to choose MOS and timeline carefully.", "Ship after graduation for basic and technical training.", "Use Tuition Assistance and GI Bill strategically."], grade12: ["Practice ASVAB and compare branch options now.", "Ask recruiters about MOS openings and bonuses.", "Set your contract and start timeline.", "Complete training and begin first assignment.", "Use education benefits while serving."], graduated: ["Take ASVAB prep and score strong this month.", "Meet multiple recruiters and compare contracts.", "Begin training pipeline and paid service.", "Build technical credentials during service.", "Use GI Bill after service for next step."] }, startToday: ["Take a free ASVAB practice test online.", "Compare jobs on official branch websites.", "Talk to a veteran you trust about real pros/cons."] },
  { id: "emt-paramedic", title: "EMT / Paramedic", tagline: "You respond fast in emergencies and keep people alive.", salaryRange: { min: 35000, max: 72000, entry: 38000 }, educationPath: "EMT certificate first (3-6 months), paramedic training next (1-2 years).", educationCost: "$1,000-$3,000 for EMT, often grant-funded; paramedic path often Pell-eligible.", timeToEntry: "3-6 months", values: ["helping", "adventure", "health", "community"], accessibilityScore: 8, dayInTheLife: "Calls vary from minor injuries to life-threatening emergencies. You assess quickly, stabilize patients, and coordinate with hospitals. Work is high-pressure and meaningful.", realPersonStory: { quote: "I started with an EMT class and later moved into paramedic training with employer help.", name: "Brianna", age: 24, background: "From rural Georgia; entered emergency medicine early" }, growthOutlook: "Stable", localOpportunities: "EMS agencies, fire departments, hospital transport units, and private ambulance services.", financialAidNote: "WIOA often covers EMT training; many employers sponsor paramedic advancement.", onetUrl: "https://www.onetonline.org/link/summary/29-2040.00", pathSteps: { grade11: ["Find EMT programs that fit your age and schedule.", "Use summer for EMT coursework where possible.", "Build volunteer or ride-along exposure in 12th grade.", "Work as EMT after graduation.", "Advance to paramedic for higher pay."], grade12: ["Apply now to EMT classes near you.", "Secure WIOA or local grant support.", "Complete training and certification after graduation.", "Start EMT role and gather field hours.", "Enter paramedic training with employer support."], graduated: ["Start EMT training this month.", "Pass certification and begin applying immediately.", "Work in EMS and build emergency response skills.", "Ask about paramedic sponsorship.", "Move into paramedic role in 2-4 years."] }, startToday: ["Search local EMT programs and next start dates.", "Review NREMT exam requirements.", "Ask local fire/EMS about volunteer pathways."] },
  { id: "carpenter", title: "Carpenter", tagline: "You build structures, interiors, and finishes that last.", salaryRange: { min: 38000, max: 85000, entry: 42000 }, educationPath: "Vocational program or union apprenticeship.", educationCost: "$1,500-$10,000 for school; union apprenticeships are typically tuition-free and paid.", timeToEntry: "6 months to 4 years", values: ["independence", "stability", "technology", "leadership"], accessibilityScore: 8, dayInTheLife: "You read plans, measure, cut, install, and solve on-site construction problems. Work can range from framing to finish carpentry and can lead to crew leadership.", realPersonStory: { quote: "I joined a paid apprenticeship and grew into a crew role with real wages and long-term stability.", name: "Victor", age: 27, background: "From South Chicago; union apprenticeship route" }, growthOutlook: "Stable", localOpportunities: "Residential and commercial construction sites in every metro area.", financialAidNote: "Union apprenticeship paths pay while you learn; public program routes can be grant-supported.", onetUrl: "https://www.onetonline.org/link/summary/47-2031.00", pathSteps: { grade11: ["Take any shop or construction class available now.", "Connect with local union training center this summer.", "Apply during 12th grade for apprenticeship openings.", "Start apprenticeship or vocational track after graduation.", "Reach journeyman level and move into leadership."], grade12: ["Review local apprenticeship requirements now.", "Gather any construction experience or references.", "Apply early for next apprenticeship cohort.", "Start paid learning and skill progression.", "Complete apprenticeship and raise earnings significantly."], graduated: ["Contact local union hall this month.", "Apply and prepare for interview/testing.", "Start paid apprenticeship when accepted.", "Build trade skills and safety credentials.", "Advance to journeyman and supervisor roles."] }, startToday: ["Find your local carpenters union training center.", "Observe nearby job-site trade roles to compare fit.", "Build a small project at home to test interest."] },
  { id: "auto-mechanic", title: "Auto / Diesel Mechanic", tagline: "You diagnose and fix vehicles people rely on every day.", salaryRange: { min: 35000, max: 80000, entry: 40000 }, educationPath: "Automotive certificate/associate plus ASE certifications.", educationCost: "$2,000-$15,000 with Pell options at public colleges.", timeToEntry: "6 months to 2 years", values: ["technology", "independence", "stability", "money"], accessibilityScore: 8, dayInTheLife: "You inspect vehicles, run diagnostics, repair systems, and explain fixes. Work mixes hands-on repair and technical troubleshooting, with EV demand increasing.", realPersonStory: { quote: "I learned from online videos, got ASE-certified, and moved into diagnostics with strong pay growth.", name: "Carlos", age: 28, background: "From San Antonio; self-taught start" }, growthOutlook: "Stable", localOpportunities: "Repair shops, dealerships, fleets, transit, and logistics companies.", financialAidNote: "Pell and workforce grants can support automotive training; dealership pipelines can sponsor training.", onetUrl: "https://www.onetonline.org/link/summary/49-3023.00", pathSteps: { grade11: ["Take school auto classes if available.", "Practice basic maintenance this summer.", "Research community college and dealer programs in 12th grade.", "Start formal training after graduation.", "Use ASE certifications to climb pay levels."], grade12: ["Apply to automotive programs now.", "Complete FAFSA and check sponsored options.", "Begin training after graduation.", "Pass early ASE certifications.", "Specialize (diagnostics/EV/diesel) for better pay."], graduated: ["Find nearest automotive program this month.", "Work part-time in a shop while training.", "Earn ASE certs and start technician role.", "Build specialty skills for diagnostics or EV.", "Move to master-tech or lead role."] }, startToday: ["Do a simple maintenance task with a tutorial.", "Review ASE certification tracks on ase.com.", "Search manufacturer-sponsored training programs near you."] },
  { id: "police-officer", title: "Police Officer", tagline: "You respond to emergencies and protect community safety.", salaryRange: { min: 50000, max: 100000, entry: 58000 }, educationPath: "HS diploma/GED plus academy; some departments require credits.", educationCost: "Many departments pay for academy and reimburse training costs.", timeToEntry: "6-18 months", values: ["justice", "community", "stability", "leadership"], accessibilityScore: 7, dayInTheLife: "You answer calls, de-escalate conflict, file reports, and work with community partners. The role is mentally and physically demanding and requires strong judgment.", realPersonStory: { quote: "I joined to serve the same neighborhoods I grew up in and focus on safer, more human policing.", name: "Nadia", age: 25, background: "From Newark; community-centered policing focus" }, growthOutlook: "Stable", localOpportunities: "City police, sheriff offices, transit and campus safety departments.", financialAidNote: "Departments often sponsor academy training and provide tuition support for continued education.", onetUrl: "https://www.onetonline.org/link/summary/33-3051.00", pathSteps: { grade11: ["Check Explorer/Cadet programs in your area.", "Review hiring standards and age requirements.", "Build fitness and clean-record profile in 12th grade.", "Apply after graduation when eligible.", "Complete probation and explore special units."], grade12: ["Review local recruitment requirements now.", "Apply for cadet/civilian pipeline opportunities.", "Prepare physical and written test readiness.", "Enter academy when hired.", "Build years of service toward specialized roles."], graduated: ["Visit official department hiring pages this month.", "Prepare for testing, fitness, and background process.", "Apply early due to long timelines.", "Complete academy and probation.", "Pursue specialty or advancement tracks."] }, startToday: ["Find your city recruitment page and requirements.", "Look up physical agility standards and start training.", "Explore local explorer/cadet opportunities."] },
  { id: "it-support", title: "IT Support Specialist", tagline: "You keep devices, systems, and users running smoothly.", salaryRange: { min: 40000, max: 75000, entry: 45000 }, educationPath: "Google IT certificate and/or CompTIA A+; degree optional.", educationCost: "Low-cost or free online certificate paths plus exam fees.", timeToEntry: "3-6 months", values: ["technology", "learning", "stability", "helping"], accessibilityScore: 9, dayInTheLife: "You troubleshoot tickets, restore access, resolve hardware/software issues, and document fixes. This is a strong entry point into cybersecurity, cloud, and networking.", realPersonStory: { quote: "I used free/low-cost certification paths, landed help desk work, then moved into cybersecurity.", name: "Tyrese", age: 22, background: "From Cleveland; entered tech without degree" }, growthOutlook: "Stable", localOpportunities: "Schools, hospitals, businesses, government, and remote support teams.", financialAidNote: "Coursera aid and workforce vouchers can cover training and certification costs.", onetUrl: "https://www.onetonline.org/link/summary/15-1232.00", pathSteps: { grade11: ["Start Google IT certificate now.", "Study A+ with free resources over summer.", "Attempt A+ during 12th grade.", "Apply to help desk roles after graduation.", "Add Network+ or Security+ for salary growth."], grade12: ["Begin certificate now and keep weekly pace.", "Study for A+ before graduation.", "Pass cert and apply after graduation.", "Get first IT role and build ticketing experience.", "Add Security+/Network+ to level up."], graduated: ["Start Google IT certificate this month.", "Prepare and pass CompTIA A+.", "Apply to local and remote help desk jobs.", "Build one year of IT support experience.", "Advance into cybersecurity/networking tracks."] }, startToday: ["Apply for Coursera financial aid and start Google IT.", "Use free A+ study channels like Professor Messer.", "Read CompTIA A+ exam objectives and job outcomes."] },
  { id: "phlebotomist", title: "Phlebotomist", tagline: "You draw blood accurately and help patients stay calm.", salaryRange: { min: 33000, max: 52000, entry: 36000 }, educationPath: "Phlebotomy certificate and CPT certification.", educationCost: "$700-$3,500, often supported by workforce grants.", timeToEntry: "4-8 months", values: ["health", "helping", "stability", "learning"], accessibilityScore: 9, dayInTheLife: "You collect samples, label precisely, and support patient comfort in labs, clinics, and hospitals. Accuracy and communication are key.", realPersonStory: { quote: "Phlebotomy let me enter healthcare fast, then use employer support for my next credential.", name: "Aaliyah", age: 22, background: "From Philadelphia; used this as healthcare entry point" }, growthOutlook: "Stable", localOpportunities: "Hospitals, blood labs, diagnostics centers, and clinics.", financialAidNote: "WIOA and employer-sponsored training often cover costs.", onetUrl: "https://www.onetonline.org/link/summary/31-9097.00", pathSteps: { grade11: ["Check if local health pathway includes phlebotomy exposure.", "Research certificate programs this summer.", "Apply during 12th grade for post-grad cohort.", "Complete certificate and CPT after graduation.", "Use experience to move into broader lab/health tracks."], grade12: ["Find nearby phlebotomy programs now.", "Apply for WIOA or local aid before enrolling.", "Complete training after graduation.", "Get CPT and begin first role.", "Use tuition support for next healthcare credential."], graduated: ["Enroll in a phlebotomy program this month.", "Complete certification quickly.", "Apply to labs/hospitals right away.", "Gain experience and ask about advancement aid.", "Bridge into higher-paying clinical roles."] }, startToday: ["Look up CPT certification requirements.", "Search diagnostics employers with training tracks.", "Watch real phlebotomy workflow videos."] },
  { id: "real-estate-agent", title: "Real Estate Agent", tagline: "You help people buy and sell homes and earn per deal.", salaryRange: { min: 30000, max: 120000, entry: 38000 }, educationPath: "State pre-licensing course plus licensing exam.", educationCost: "$200-$1,000 course costs plus exam fees.", timeToEntry: "3-6 months", values: ["independence", "money", "community", "leadership"], accessibilityScore: 7, dayInTheLife: "You show homes, guide offers, negotiate terms, and support clients through complex decisions. Early years are heavily relationship-driven and hustle-based.", realPersonStory: { quote: "I specialized in first-time buyers in my own community and grew into a strong income within a few years.", name: "Simone", age: 29, background: "From the Bronx; focused on local buyers" }, growthOutlook: "Stable", localOpportunities: "Brokerages and local housing markets in every city and suburb.", financialAidNote: "Low startup costs; some workforce programs or brokerages support new agent training.", onetUrl: "https://www.onetonline.org/link/summary/41-9022.00", pathSteps: { grade11: ["Study your local market and age requirements.", "Research state licensing process this summer.", "Start pre-licensing in 12th grade if eligible.", "Pass exam and join brokerage after graduation.", "Build referral network and niche focus."], grade12: ["Review state course-hour requirements now.", "Complete pre-licensing coursework if eligible.", "Take exam and choose a training-focused brokerage.", "Join a team for first-year mentorship and leads.", "Specialize in a market niche for growth."], graduated: ["Check your state commission site this month.", "Finish pre-licensing course and schedule exam.", "Join a brokerage with strong onboarding.", "Build your pipeline through referrals and content.", "Scale into high-performing local specialization."] }, startToday: ["Read your state real estate licensing rules.", "Track listings in your target neighborhoods daily.", "Follow a top local agent and study their process."] },
  { id: "chef", title: "Chef / Culinary Professional", tagline: "You turn food skill into leadership and creative work.", salaryRange: { min: 32000, max: 85000, entry: 38000 }, educationPath: "Start in kitchen roles immediately; culinary programs optional.", educationCost: "$2,000-$8,000 for community college culinary routes, often aid-eligible.", timeToEntry: "Immediate entry as line/prep cook", values: ["creativity", "expression", "independence", "leadership"], accessibilityScore: 8, dayInTheLife: "You prep, execute service under pressure, maintain quality, and coordinate with the kitchen team. With growth comes menu planning, staffing, and cost control.", realPersonStory: { quote: "I started in dish and prep, kept learning, and moved into kitchen leadership with no expensive private culinary degree.", name: "Rafael", age: 26, background: "From Miami; worked up through restaurant roles" }, growthOutlook: "Growing fast", localOpportunities: "Restaurants, catering, hotels, schools, and healthcare food services.", financialAidNote: "Pell Grants can support public culinary programs; many careers begin with zero tuition via on-the-job growth.", onetUrl: "https://www.onetonline.org/link/summary/35-1011.00", pathSteps: { grade11: ["Get any restaurant role to learn kitchen pace.", "Cross-train in prep over summer.", "Compare community college culinary options in 12th grade.", "Choose school or direct kitchen growth after graduation.", "Move toward sous/lead role with consistency."], grade12: ["Start working in a kitchen now if possible.", "Review affordable culinary programs and FAFSA options.", "Continue skill-building after graduation.", "Focus on speed, consistency, and station mastery.", "Move into sous/manager track over 2-3 years."], graduated: ["Apply to kitchen jobs this month.", "Build skill and reliability during first 6-12 months.", "Choose whether to add culinary coursework.", "Step into lead/sous opportunities as you progress.", "Target executive chef or business ownership path long-term."] }, startToday: ["Cook one new dish and improve it twice.", "Apply to a local prep/line role.", "Review culinary scholarship options like James Beard."] },
  { id: "early-childhood-educator", title: "Early Childhood Education Professional", tagline: "You shape early learning years that change long-term outcomes.", salaryRange: { min: 28000, max: 60000, entry: 33000 }, educationPath: "CDA credential for entry, associate degree for lead roles.", educationCost: "CDA under $500; community college ECE programs often Pell-eligible.", timeToEntry: "6 months (CDA)", values: ["helping", "family", "community", "learning"], accessibilityScore: 9, dayInTheLife: "You plan child development activities, support social and language growth, and build trust with families. The work is patient, structured, and deeply impactful.", realPersonStory: { quote: "I started as an aide, earned CDA support through my center, and advanced into a lead teacher role.", name: "Jasmine", age: 24, background: "From Richmond, CA; returned to serve local children" }, growthOutlook: "Stable", localOpportunities: "Head Start, childcare centers, pre-K classrooms, and community programs.", financialAidNote: "Head Start sponsorships, Pell Grants, and T.E.A.C.H. scholarships can fund credentials.", onetUrl: "https://www.onetonline.org/link/summary/25-2011.00", pathSteps: { grade11: ["Volunteer with childcare programs to test fit.", "Explore local Head Start and training options this summer.", "Research CDA and ECE requirements in 12th grade.", "Begin center work and CDA after graduation.", "Pursue associate degree with scholarship support."], grade12: ["Apply for part-time childcare roles now.", "Review CDA process and ECE college options.", "Start CDA and childcare work after graduation.", "Earn CDA and seek lead-track responsibilities.", "Build toward associate degree for better pay."], graduated: ["Find nearby Head Start/childcare openings this month.", "Begin CDA training and supervised hours.", "Complete CDA and continue classroom experience.", "Use scholarships for ECE degree progress.", "Advance to lead teacher/program roles."] }, startToday: ["Search Head Start centers near you.", "Review CDA requirements at cdacouncil.org.", "Volunteer with youth programs to build experience now."] },
];

export const CAREER_MAP = CAREERS.reduce<Record<string, Career>>((acc, career) => {
  acc[career.id] = career;
  return acc;
}, {});

const ONET_URLS: Record<string, string> = {
  "registered-nurse": "https://www.onetonline.org/link/summary/29-1141.00",
  electrician: "https://www.onetonline.org/link/summary/47-2111.00",
  "social-worker": "https://www.onetonline.org/link/summary/21-1029.00",
  "ux-designer": "https://www.onetonline.org/link/summary/15-1255.00",
  "medical-assistant": "https://www.onetonline.org/link/summary/31-9092.00",
  paralegal: "https://www.onetonline.org/link/summary/23-2011.00",
  "hvac-technician": "https://www.onetonline.org/link/summary/49-9021.00",
  "elementary-teacher": "https://www.onetonline.org/link/summary/25-2021.00",
  "cybersecurity-analyst": "https://www.onetonline.org/link/summary/15-1212.00",
  "dental-hygienist": "https://www.onetonline.org/link/summary/29-2021.00",
  "graphic-designer": "https://www.onetonline.org/link/summary/27-1024.00",
  "construction-manager": "https://www.onetonline.org/link/summary/11-9021.00",
  "community-health-worker": "https://www.onetonline.org/link/summary/21-1094.00",
  "software-developer": "https://www.onetonline.org/link/summary/15-1252.00",
  plumber: "https://www.onetonline.org/link/summary/47-2152.00",
  "youth-counselor": "https://www.onetonline.org/link/summary/21-1021.00",
  firefighter: "https://www.onetonline.org/link/summary/33-2011.00",
  "podcast-content-creator": "https://www.onetonline.org/link/summary/27-3043.00",
  "pharmacy-technician": "https://www.onetonline.org/link/summary/29-2052.00",
  "environmental-technician": "https://www.onetonline.org/link/summary/19-4042.00",
  cna: "https://www.onetonline.org/link/summary/31-1131.00",
  "truck-driver": "https://www.onetonline.org/link/summary/53-3032.00",
  welder: "https://www.onetonline.org/link/summary/51-4121.00",
  "wind-turbine-tech": "https://www.onetonline.org/link/summary/49-9081.00",
  cosmetologist: "https://www.onetonline.org/link/summary/39-5012.00",
  military: "https://www.onetonline.org/link/summary/55-1019.00",
  "emt-paramedic": "https://www.onetonline.org/link/summary/29-2040.00",
  carpenter: "https://www.onetonline.org/link/summary/47-2031.00",
  "auto-mechanic": "https://www.onetonline.org/link/summary/49-3023.00",
  "police-officer": "https://www.onetonline.org/link/summary/33-3051.00",
  "it-support": "https://www.onetonline.org/link/summary/15-1232.00",
  phlebotomist: "https://www.onetonline.org/link/summary/31-9097.00",
  "real-estate-agent": "https://www.onetonline.org/link/summary/41-9022.00",
  chef: "https://www.onetonline.org/link/summary/35-1011.00",
  "early-childhood-educator": "https://www.onetonline.org/link/summary/25-2011.00",
};

const RELATED: Record<string, string[]> = {
  "registered-nurse": ["medical-assistant", "pharmacy-technician"],
  electrician: ["hvac-technician", "plumber"],
  "social-worker": ["youth-counselor", "community-health-worker"],
  "ux-designer": ["graphic-designer", "software-developer"],
  "medical-assistant": ["registered-nurse", "pharmacy-technician"],
  paralegal: ["social-worker", "youth-counselor"],
  "hvac-technician": ["electrician", "plumber"],
  "elementary-teacher": ["youth-counselor", "social-worker"],
  "cybersecurity-analyst": ["software-developer", "ux-designer"],
  "dental-hygienist": ["registered-nurse", "medical-assistant"],
  "graphic-designer": ["ux-designer", "podcast-content-creator"],
  "construction-manager": ["electrician", "plumber"],
  "community-health-worker": ["social-worker", "medical-assistant"],
  "software-developer": ["cybersecurity-analyst", "ux-designer"],
  plumber: ["electrician", "hvac-technician"],
  "youth-counselor": ["social-worker", "elementary-teacher"],
  firefighter: ["community-health-worker", "registered-nurse"],
  "podcast-content-creator": ["graphic-designer", "ux-designer"],
  "pharmacy-technician": ["medical-assistant", "registered-nurse"],
  "environmental-technician": ["construction-manager", "community-health-worker"],
  cna: ["registered-nurse", "medical-assistant"],
  "truck-driver": ["construction-manager", "plumber"],
  welder: ["carpenter", "construction-manager"],
  "wind-turbine-tech": ["environmental-technician", "electrician"],
  cosmetologist: ["graphic-designer", "podcast-content-creator"],
  military: ["it-support", "police-officer"],
  "emt-paramedic": ["firefighter", "registered-nurse"],
  carpenter: ["construction-manager", "electrician"],
  "auto-mechanic": ["hvac-technician", "electrician"],
  "police-officer": ["firefighter", "youth-counselor"],
  "it-support": ["cybersecurity-analyst", "software-developer"],
  phlebotomist: ["medical-assistant", "pharmacy-technician"],
  "real-estate-agent": ["construction-manager", "community-health-worker"],
  chef: ["podcast-content-creator", "graphic-designer"],
  "early-childhood-educator": ["elementary-teacher", "youth-counselor"],
};

export function getCareerExtras(career: Career): Required<Pick<Career, "onetUrl" | "relatedCareerIds" | "pathSteps" | "startToday">> {
  const base = career.title;
  const defaultPathSteps = {
    grade11: [
      `Right now (11th grade): search local programs for ${base} and save three options with cost and timeline.`,
      "Summer before 12th: try a volunteer shift, school club, or short workshop tied to this field.",
      "12th grade: complete FAFSA early and apply to at least two low-cost programs or apprenticeships.",
      "After graduation: start training or entry-level work and ask about paid learning options.",
      "1-2 years in: earn your first credential and negotiate for your next pay jump.",
    ],
    grade12: [
      "Right now, this semester: lock in your top training option and application dates.",
      "Before graduation: submit FAFSA and ask counselors about Pell and local scholarships.",
      "Summer after graduation: begin classes, apprenticeship, or paid trainee role.",
      "Year 1: build real hours and keep every project for your portfolio/resume.",
      "2-3 years in: add an advanced credential and move toward higher-paying roles.",
    ],
    graduated: [
      "This month: apply to two fast-start programs and one paid entry role.",
      "Next 30 days: meet financial aid staff and confirm grants before signing anything.",
      "Month 2-6: complete core training while building work samples and references.",
      "Year 1: secure full-time placement in the field.",
      "Year 2+: specialize to unlock stronger pay and leadership options.",
    ],
  };
  return {
    onetUrl: career.onetUrl ?? ONET_URLS[career.id],
    relatedCareerIds: career.relatedCareerIds ?? RELATED[career.id] ?? [],
    pathSteps: career.pathSteps ?? defaultPathSteps,
    startToday: career.startToday ?? [
      `Search \"${base} high school internship near me\" and save three leads.`,
      `Watch one real day-in-the-life ${base.toLowerCase()} video and write down what feels exciting and hard.`,
      "Message one person in the field on LinkedIn or ask your counselor for a local contact.",
    ],
  };
}
