"use client";

import { useMemo } from "react";
import Layout from "@/components/Layout";
import { CAREER_MAP } from "@/lib/careers";
import { matchCareers } from "@/lib/matching";
import { SITUATION_STORAGE_KEY, VALUES_STORAGE_KEY } from "@/lib/storage";
import { VALUE_OPTIONS } from "@/lib/values";

export default function SharePage() {
  const data = useMemo(() => {
    if (typeof window === "undefined") return null;
    const values = JSON.parse(window.localStorage.getItem(VALUES_STORAGE_KEY) ?? "[]") as string[];
    const situation = JSON.parse(window.localStorage.getItem(SITUATION_STORAGE_KEY) ?? "null") as {
      grade?: string;
      firstGen?: string;
      workStatus?: string;
    } | null;
    return { values, situation, careers: matchCareers(values) };
  }, []);

  const selectedValues = (data?.values ?? []).map((id) => VALUE_OPTIONS.find((v) => v.id === id)).filter(Boolean);

  const summaryText = [
    "Blueprint Student Career Exploration Summary",
    `Grade: ${data?.situation?.grade ?? "N/A"}`,
    `First-gen: ${data?.situation?.firstGen ?? "N/A"}`,
    `Working now: ${data?.situation?.workStatus ?? "N/A"}`,
    `Top values: ${selectedValues.map((v) => `${v?.emoji} ${v?.name}`).join(", ")}`,
    "Matches:",
    ...(data?.careers ?? []).map((career) => `- ${career.title}: $${Math.round(career.salaryRange.min / 1000)}K-$${Math.round(career.salaryRange.max / 1000)}K/year · ${career.timeToEntry}`),
    "Generated by Blueprint Career Explorer · blueprintcareer.app",
  ].join("\n");

  return (
    <div className="min-h-screen bg-[#F4F7FC]">
      <Layout>
        <section className="space-y-4 rounded-2xl bg-white p-6 shadow-sm">
          <h1 className="font-serif text-3xl font-bold text-[#1E2761]">Student Career Exploration Summary</h1>
          <p className="text-sm text-[#5A6A85]">Blueprint does not store your name, school, or any personal information.</p>
          <p className="text-sm text-[#2D3748]">Grade: {data?.situation?.grade ?? "-"} · First-gen: {data?.situation?.firstGen ?? "-"} · Work: {data?.situation?.workStatus ?? "-"}</p>

          <div className="flex flex-wrap gap-2">{selectedValues.map((v) => <span key={v?.id} className="rounded-full border border-[#4472C4] px-3 py-1 text-sm text-[#1E2761]">{v?.emoji} {v?.name}</span>)}</div>

          <div className="space-y-2">{(data?.careers ?? []).map((career) => <p key={career.id} className="text-sm text-[#1A1A2E]">{career.title} · ${Math.round(career.salaryRange.min / 1000)}K-${Math.round(career.salaryRange.max / 1000)}K/year · {career.timeToEntry}</p>)}</div>

          <button type="button" className="min-h-12 rounded-xl border-2 border-[#E8A020] px-4 font-semibold text-[#1A1A2E]" onClick={() => navigator.clipboard.writeText(summaryText)}>Copy summary text</button>
        </section>
      </Layout>
    </div>
  );
}
